### ISSUE TITLE
Cashier cannot sell tickets to events with no show

### ISSUE THREAD

**Issue by anderfernandes** [anderfernandes/astral#32]
Cashier cannot sell tickets to events with no show. Make it so that we can and change the title of the event to the old memo field if the event's show is a no show.

**Comment by L0adcode** [comment]
Hey man, you still have me on your mailing list. From github.

**Comment by anderfernandes** [comment]
My bad @L0adcode, I will take you out of it.

**Comment by anderfernandes** [comment]
The order in which the shows appear in cashier is not by date.
